In [163]:
n=512

In [166]:
n = 512
for j in [1,2,4,8]:
    for i in range(100000):
        q = (3*n*i/j)+1

        if q > 2^13:
            print("===============end===============");
            break;

        if q in Primes():
            print(j,":",q)

1 : 7681
===============end===============
2 : 769
2 : 7681
===============end===============
4 : 769
4 : 1153
4 : 2689
4 : 3457
4 : 4993
4 : 6529
4 : 7297
4 : 7681
===============end===============
8 : 193
8 : 577
8 : 769
8 : 1153
8 : 2113
8 : 2689
8 : 3457
8 : 4801
8 : 4993
8 : 5569
8 : 5953
8 : 6337
8 : 6529
8 : 7297
8 : 7489
8 : 7681
8 : 7873
===============end===============

In [168]:
factor(576)

2^6 * 3^2

In [169]:
n = 576 #
for j in [1,2,3,4,6,8,9,12,16]:
    for i in range(100000):
        q = (3*n*i/j)+1

        if q > 2^13:
            print("===============end===============");
            break;

        if q in Primes():
            print(j,":",q)

1 : 3457
===============end===============
2 : 2593
2 : 3457
===============end===============
3 : 577
3 : 1153
3 : 3457
3 : 6337
3 : 7489
===============end===============
4 : 433
4 : 1297
4 : 2161
4 : 2593
4 : 3457
4 : 3889
4 : 6481
===============end===============
6 : 577
6 : 1153
6 : 2017
6 : 2593
6 : 3169
6 : 3457
6 : 6337
6 : 7489
===============end===============
8 : 433
8 : 1297
8 : 2161
8 : 2377
8 : 2593
8 : 3457
8 : 3673
8 : 3889
8 : 4969
8 : 6481
8 : 7129
8 : 7561
8 : 7993
===============end===============
9 : 193
9 : 577
9 : 769
9 : 1153
9 : 2113
9 : 2689
9 : 3457
9 : 4801
9 : 4993
9 : 5569
9 : 5953
9 : 6337
9 : 6529
9 : 7297
9 : 7489
9 : 7681
9 : 7873
===============end===============
12 : 433
12 : 577
12 : 1009
12 : 1153
12 : 1297
12 : 1873
12 : 2017
12 : 2161
12 : 2593
12 : 3169
12 : 3313
12 : 3457
12 : 3889
12 : 4177
12 : 6337
12 : 6481
12 : 7057
12 : 7489
===============end===============
16 : 109
16 : 433
16 : 541
16 : 757
16 : 1297
16 : 1621
16 : 2053
16 : 2161
16 : 2269
16 : 2377
16 : 2593
16 : 2917
16 : 3457
16 : 3673
16 : 3889
16 : 4861
16 : 4969
16 : 5077
16 : 6373
16 : 6481
16 : 7129
16 : 7237
16 : 7561
16 : 7669
16 : 7993
16 : 8101
===============end===============

In [170]:
factor(648)

2^3 * 3^4

In [171]:
n = 648 #
for j in [1,2,3,4,6,8,9,12]:
    for i in range(100000):
        q = (3*n*i/j)+1

        if q > 2^13:
            print("===============end===============");
            break;

        if q in Primes():
            print(j,":",q)

1 : 3889
===============end===============
2 : 2917
2 : 3889
2 : 4861
===============end===============
3 : 1297
3 : 2593
3 : 3889
3 : 6481
3 : 7129
===============end===============
4 : 487
4 : 1459
4 : 2917
4 : 3889
4 : 4861
4 : 5347
===============end===============
6 : 1297
6 : 1621
6 : 2269
6 : 2593
6 : 2917
6 : 3889
6 : 4861
6 : 6481
6 : 7129
6 : 8101
===============end===============
8 : 487
8 : 1459
8 : 2917
8 : 3889
8 : 4861
8 : 5347
===============end===============
9 : 433
9 : 1297
9 : 2161
9 : 2377
9 : 2593
9 : 3457
9 : 3673
9 : 3889
9 : 4969
9 : 6481
9 : 7129
9 : 7561
9 : 7993
===============end===============
12 : 163
12 : 487
12 : 811
12 : 1297
12 : 1459
12 : 1621
12 : 1783
12 : 2269
12 : 2593
12 : 2917
12 : 3079
12 : 3727
12 : 3889
12 : 4051
12 : 4861
12 : 5023
12 : 5347
12 : 6481
12 : 6967
12 : 7129
12 : 8101
===============end===============

In [172]:
factor(768)

2^8 * 3

In [179]:
n = 768 #
for j in [1,2,3,4,6,8,12,16]:
    for i in range(100000):
        q = (3*n*i/j)+1

        if q > 2^13:
            print("===============end===============");
            break;

        if q in Primes():
            print(j,":",q)

===============end===============
2 : 1153
2 : 3457
===============end===============
3 : 769
3 : 7681
===============end===============
4 : 577
4 : 1153
4 : 3457
4 : 6337
4 : 7489
===============end===============
6 : 769
6 : 1153
6 : 2689
6 : 3457
6 : 4993
6 : 6529
6 : 7297
6 : 7681
===============end===============
8 : 577
8 : 1153
8 : 2017
8 : 2593
8 : 3169
8 : 3457
8 : 6337
8 : 7489
===============end===============
12 : 193
12 : 577
12 : 769
12 : 1153
12 : 2113
12 : 2689
12 : 3457
12 : 4801
12 : 4993
12 : 5569
12 : 5953
12 : 6337
12 : 6529
12 : 7297
12 : 7489
12 : 7681
12 : 7873
===============end===============
16 : 433
16 : 577
16 : 1009
16 : 1153
16 : 1297
16 : 1873
16 : 2017
16 : 2161
16 : 2593
16 : 3169
16 : 3313
16 : 3457
16 : 3889
16 : 4177
16 : 6337
16 : 6481
16 : 7057
16 : 7489
===============end===============

In [180]:
factor(864)

2^5 * 3^3

In [181]:
n = 864 #
for j in [1,2,3,4,6,8,9,12,16]:
    for i in range(100000):
        q = (3*n*i/j)+1

        if q > 2^13:
            print("===============end===============");
            break;

        if q in Primes():
            print(j,":",q)

1 : 2593
===============end===============
2 : 1297
2 : 2593
2 : 3889
2 : 6481
===============end===============
3 : 2593
3 : 3457
===============end===============
4 : 1297
4 : 2593
4 : 3889
4 : 6481
4 : 7129
===============end===============
6 : 433
6 : 1297
6 : 2161
6 : 2593
6 : 3457
6 : 3889
6 : 6481
===============end===============
8 : 1297
8 : 1621
8 : 2269
8 : 2593
8 : 2917
8 : 3889
8 : 4861
8 : 6481
8 : 7129
8 : 8101
===============end===============
9 : 577
9 : 1153
9 : 2017
9 : 2593
9 : 3169
9 : 3457
9 : 6337
9 : 7489
===============end===============
12 : 433
12 : 1297
12 : 2161
12 : 2377
12 : 2593
12 : 3457
12 : 3673
12 : 3889
12 : 4969
12 : 6481
12 : 7129
12 : 7561
12 : 7993
===============end===============
16 : 163
16 : 487
16 : 811
16 : 1297
16 : 1459
16 : 1621
16 : 1783
16 : 2269
16 : 2593
16 : 2917
16 : 3079
16 : 3727
16 : 3889
16 : 4051
16 : 4861
16 : 5023
16 : 5347
16 : 6481
16 : 6967
16 : 7129
16 : 8101
===============end===============

In [182]:
factor(972)

2^2 * 3^5

In [185]:
n = 972 #
for j in [1,2,3,4,6,9,12]:
    for i in range(100000):
        q = (3*n*i/j)+1

        if q > 2^13:
            print("===============end===============");
            break;

        if q in Primes():
            print(j,":",q)

1 : 2917
===============end===============
2 : 1459
2 : 2917
===============end===============
3 : 2917
3 : 3889
3 : 4861
===============end===============
4 : 1459
4 : 2917
===============end===============
6 : 487
6 : 1459
6 : 2917
6 : 3889
6 : 4861
6 : 5347
===============end===============
9 : 1297
9 : 1621
9 : 2269
9 : 2593
9 : 2917
9 : 3889
9 : 4861
9 : 6481
9 : 7129
9 : 8101
===============end===============
12 : 487
12 : 1459
12 : 2917
12 : 3889
12 : 4861
12 : 5347
===============end===============

In [186]:
factor(1024)

2^10

In [187]:
n = 1024 #
for j in [1,2,4,8,16]:
    for i in range(100000):
        q = (3*n*i/j)+1

        if q > 2^13:
            print("===============end===============");
            break;

        if q in Primes():
            print(j,":",q)

===============end===============
2 : 7681
===============end===============
4 : 769
4 : 7681
===============end===============
8 : 769
8 : 1153
8 : 2689
8 : 3457
8 : 4993
8 : 6529
8 : 7297
8 : 7681
===============end===============
16 : 193
16 : 577
16 : 769
16 : 1153
16 : 2113
16 : 2689
16 : 3457
16 : 4801
16 : 4993
16 : 5569
16 : 5953
16 : 6337
16 : 6529
16 : 7297
16 : 7489
16 : 7681
16 : 7873
===============end===============

In [183]:
factor(1152)

2^7 * 3^2

In [189]:
n = 1152 #
for j in [1,2,3,4,6,8,9,12,16]:
    for i in range(100000):
        q = (3*n*i/j)+1

        if q > 2^13:
            print("===============end===============");
            break;

        if q in Primes():
            print(j,":",q)

1 : 3457
===============end===============
2 : 3457
===============end===============
3 : 1153
3 : 3457
===============end===============
4 : 2593
4 : 3457
===============end===============
6 : 577
6 : 1153
6 : 3457
6 : 6337
6 : 7489
===============end===============
8 : 433
8 : 1297
8 : 2161
8 : 2593
8 : 3457
8 : 3889
8 : 6481
===============end===============
9 : 769
9 : 1153
9 : 2689
9 : 3457
9 : 4993
9 : 6529
9 : 7297
9 : 7681
===============end===============
12 : 577
12 : 1153
12 : 2017
12 : 2593
12 : 3169
12 : 3457
12 : 6337
12 : 7489
===============end===============
16 : 433
16 : 1297
16 : 2161
16 : 2377
16 : 2593
16 : 3457
16 : 3673
16 : 3889
16 : 4969
16 : 6481
16 : 7129
16 : 7561
16 : 7993
===============end===============

In [184]:
factor(1296)

2^4 * 3^4

In [1]:
n = 1296 #
for j in [1,2,3,4,6,8,9,12,16]:
    for i in range(100000):
        q = (3*n*i/j)+1

        if q > 2^13:
            print("===============end===============");
            break;

        if q in Primes():
            print(j,":",q)

1 : 3889
===============end===============
2 : 3889
===============end===============
3 : 1297
3 : 2593
3 : 3889
3 : 6481
===============end===============
4 : 2917
4 : 3889
4 : 4861
===============end===============
6 : 1297
6 : 2593
6 : 3889
6 : 6481
6 : 7129
===============end===============
8 : 487
8 : 1459
8 : 2917
8 : 3889
8 : 4861
8 : 5347
===============end===============
9 : 433
9 : 1297
9 : 2161
9 : 2593
9 : 3457
9 : 3889
9 : 6481
===============end===============
12 : 1297
12 : 1621
12 : 2269
12 : 2593
12 : 2917
12 : 3889
12 : 4861
12 : 6481
12 : 7129
12 : 8101
===============end===============
16 : 487
16 : 1459
16 : 2917
16 : 3889
16 : 4861
16 : 5347
===============end===============

In [1]:
table = []
i = 0
for a in range(12):
    for b in range(12):
        table = table + [2^a*3^b]

table.sort()

In [2]:
print(table)

[1, 2, 3, 4, 6, 8, 9, 12, 16, 18, 24, 27, 32, 36, 48, 54, 64, 72, 81, 96, 108, 128, 144, 162, 192, 216, 243, 256, 288, 324, 384, 432, 486, 512, 576, 648, 729, 768, 864, 972, 1024, 1152, 1296, 1458, 1536, 1728, 1944, 2048, 2187, 2304, 2592, 2916, 3072, 3456, 3888, 4374, 4608, 5184, 5832, 6144, 6561, 6912, 7776, 8748, 9216, 10368, 11664, 13122, 13824, 15552, 17496, 18432, 19683, 20736, 23328, 26244, 27648, 31104, 34992, 39366, 41472, 46656, 52488, 55296, 59049, 62208, 69984, 78732, 82944, 93312, 104976, 118098, 124416, 139968, 157464, 165888, 177147, 186624, 209952, 236196, 248832, 279936, 314928, 354294, 373248, 419904, 472392, 497664, 559872, 629856, 708588, 746496, 839808, 944784, 1119744, 1259712, 1417176, 1492992, 1679616, 1889568, 2239488, 2519424, 2834352, 3359232, 3779136, 4478976, 5038848, 5668704, 6718464, 7558272, 10077696, 11337408, 13436928, 15116544, 20155392, 22674816, 30233088, 40310784, 45349632, 60466176, 90699264, 120932352, 181398528, 362797056]

In [5]:
for a in range(144):
    table[a] = table[a]/32

In [6]:
print(table)

[1/32, 1/16, 3/32, 1/8, 3/16, 1/4, 9/32, 3/8, 1/2, 9/16, 3/4, 27/32, 1, 9/8, 3/2, 27/16, 2, 9/4, 81/32, 3, 27/8, 4, 9/2, 81/16, 6, 27/4, 243/32, 8, 9, 81/8, 12, 27/2, 243/16, 16, 18, 81/4, 729/32, 24, 27, 243/8, 32, 36, 81/2, 729/16, 48, 54, 243/4, 64, 2187/32, 72, 81, 729/8, 96, 108, 243/2, 2187/16, 144, 162, 729/4, 192, 6561/32, 216, 243, 2187/8, 288, 324, 729/2, 6561/16, 432, 486, 2187/4, 576, 19683/32, 648, 729, 6561/8, 864, 972, 2187/2, 19683/16, 1296, 1458, 6561/4, 1728, 59049/32, 1944, 2187, 19683/8, 2592, 2916, 6561/2, 59049/16, 3888, 4374, 19683/4, 5184, 177147/32, 5832, 6561, 59049/8, 7776, 8748, 19683/2, 177147/16, 11664, 13122, 59049/4, 15552, 17496, 19683, 177147/8, 23328, 26244, 59049/2, 34992, 39366, 177147/4, 46656, 52488, 59049, 69984, 78732, 177147/2, 104976, 118098, 139968, 157464, 177147, 209952, 236196, 314928, 354294, 419904, 472392, 629856, 708588, 944784, 1259712, 1417176, 1889568, 2834352, 3779136, 5668704, 11337408]